networks:
  global:
    driver: bridge

services:
  servicio-database:
    image: mysql:8.0
    container_name: servicio-database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - global
    volumes:
      - ./database/datos:/var/lib/mysql
      - ./database/configuracion/configuracion.sql:/docker-entrypoint-initdb.d/init.sql:ro
    mem_limit: 256m
    cpus: 0.25

  servicio-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: servicio-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - global
    depends_on:
      - servicio-database
    mem_limit: 256m
    cpus: 0.25

volumes:
  datos:
