USE slaanesh;

CREATE TABLE IF NOT EXISTS usuario (
    id INT UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    gmail VARCHAR(40) NOT NULL UNIQUE,
    passwordhas VARCHAR(255) NOT NULL
);
